version: "3.9"

services:
  database:
    image: postgres
    container_name: cashme_db
    ports:
     - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cashmedb
    volumes:
     - pgdata:/data/postgres
  app:
    build: .
    container_name: cashme_app
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on:
      - database

volumes: 
  pgdata:
    driver: local